postgresql:
    build: ./postgresql/install
    ports:
        - "5432:5432"

nessus:
    build: ./nessus/install
    ports:
        - "8834:8834" 

django:
    build: ./django/install
    volumes:
        - ../sources/:/var/www/html/soc/
    ports:
        - "443:443"
    links:
        - postgresql
        - nessus
